import { Plant, Pet, Tool } from './store';

export const PLANTS: Plant[] = [
  // Common Plants
  {
    id: 'carrot',
    name: 'Carrot',
    icon: '🥕',
    rarity: 'common',
    growthTime: 30000, // 30 seconds
    sellPrice: 5,
    buyPrice: 2,
    stage: 'seed',
    waterNeeded: 1,
    soilType: 'normal',
    season: ['spring', 'fall'],
    xpGained: 5,
    description: 'A basic orange vegetable that grows quickly',
    unlockLevel: 1,
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    icon: '🥬',
    rarity: 'common',
    growthTime: 25000,
    sellPrice: 4,
    buyPrice: 2,
    stage: 'seed',
    waterNeeded: 2,
    soilType: 'normal',
    season: ['spring', 'summer'],
    xpGained: 4,
    description: 'Fresh green leafy vegetable',
    unlockLevel: 1,
  },
  {
    id: 'tomato',
    name: 'Tomato',
    icon: '🍅',
    rarity: 'common',
    growthTime: 45000,
    sellPrice: 8,
    buyPrice: 3,
    stage: 'seed',
    waterNeeded: 2,
    soilType: 'normal',
    season: ['summer'],
    xpGained: 8,
    description: 'Juicy red fruit perfect for salads',
    unlockLevel: 3,
  },
  
  // Uncommon Plants
  {
    id: 'corn',
    name: 'Corn',
    icon: '🌽',
    rarity: 'uncommon',
    growthTime: 60000,
    sellPrice: 15,
    buyPrice: 6,
    stage: 'seed',
    waterNeeded: 3,
    soilType: 'fertile',
    season: ['summer'],
    xpGained: 12,
    description: 'Tall stalks with golden kernels',
    unlockLevel: 5,
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    icon: '🎃',
    rarity: 'uncommon',
    growthTime: 90000,
    sellPrice: 25,
    buyPrice: 10,
    stage: 'seed',
    waterNeeded: 4,
    soilType: 'fertile',
    season: ['fall'],
    xpGained: 20,
    description: 'Large orange gourd perfect for decorations',
    unlockLevel: 8,
  },
  
  // Rare Plants
  {
    id: 'blueberry',
    name: 'Blueberry Bush',
    icon: '🫐',
    rarity: 'rare',
    growthTime: 120000,
    sellPrice: 50,
    buyPrice: 20,
    stage: 'seed',
    waterNeeded: 3,
    soilType: 'acidic',
    season: ['summer'],
    xpGained: 35,
    description: 'Sweet blue berries with antioxidants',
    unlockLevel: 12,
  },
  {
    id: 'avocado',
    name: 'Avocado Tree',
    icon: '🥑',
    rarity: 'rare',
    growthTime: 180000,
    sellPrice: 75,
    buyPrice: 30,
    stage: 'seed',
    waterNeeded: 4,
    soilType: 'tropical',
    season: ['spring', 'summer'],
    xpGained: 50,
    description: 'Creamy green fruit packed with healthy fats',
    unlockLevel: 15,
  },
  
  // Epic Plants
  {
    id: 'golden_apple',
    name: 'Golden Apple Tree',
    icon: '🍎',
    rarity: 'epic',
    growthTime: 300000,
    sellPrice: 200,
    buyPrice: 80,
    stage: 'seed',
    waterNeeded: 5,
    soilType: 'magical',
    season: ['all'],
    xpGained: 100,
    description: 'Mystical golden apples with healing properties',
    unlockLevel: 20,
  },
  {
    id: 'crystal_flower',
    name: 'Crystal Flower',
    icon: '💎',
    rarity: 'epic',
    growthTime: 240000,
    sellPrice: 150,
    buyPrice: 60,
    stage: 'seed',
    waterNeeded: 6,
    soilType: 'magical',
    season: ['winter'],
    xpGained: 80,
    description: 'Beautiful crystalline petals that shimmer',
    unlockLevel: 18,
  },
  
  // Legendary Plants
  {
    id: 'rainbow_rose',
    name: 'Rainbow Rose',
    icon: '🌹',
    rarity: 'legendary',
    growthTime: 600000,
    sellPrice: 1000,
    buyPrice: 400,
    stage: 'seed',
    waterNeeded: 10,
    soilType: 'celestial',
    season: ['all'],
    xpGained: 500,
    description: 'Legendary flower that changes colors with the light',
    unlockLevel: 30,
  },
  {
    id: 'money_tree',
    name: 'Money Tree',
    icon: '💰',
    rarity: 'legendary',
    growthTime: 480000,
    sellPrice: 2000,
    buyPrice: 800,
    stage: 'seed',
    waterNeeded: 8,
    soilType: 'golden',
    season: ['all'],
    xpGained: 1000,
    description: 'Mythical tree that grows coins instead of fruit',
    unlockLevel: 35,
  },
];

export const PETS: Pet[] = [
  // Common Pets
  {
    id: 'rabbit',
    name: 'Garden Rabbit',
    icon: '🐰',
    rarity: 'common',
    ability: 'Speed Boost',
    abilityDescription: 'Increases movement speed by 20%',
    speed: 1.2,
    efficiency: 1.1,
    unlockLevel: 1,
    price: 50,
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    icon: '🦋',
    rarity: 'common',
    ability: 'Pollination',
    abilityDescription: 'Increases crop yield by 10%',
    speed: 1.0,
    efficiency: 1.1,
    unlockLevel: 3,
    price: 75,
  },
  
  // Uncommon Pets
  {
    id: 'bee',
    name: 'Busy Bee',
    icon: '🐝',
    rarity: 'uncommon',
    ability: 'Auto Pollinate',
    abilityDescription: 'Automatically pollinates nearby plants',
    speed: 1.1,
    efficiency: 1.25,
    unlockLevel: 7,
    price: 150,
  },
  {
    id: 'ladybug',
    name: 'Ladybug',
    icon: '🐞',
    rarity: 'uncommon',
    ability: 'Pest Control',
    abilityDescription: 'Protects plants from pests',
    speed: 1.0,
    efficiency: 1.2,
    unlockLevel: 10,
    price: 200,
  },
  
  // Rare Pets
  {
    id: 'owl',
    name: 'Wise Owl',
    icon: '🦉',
    rarity: 'rare',
    ability: 'XP Boost',
    abilityDescription: 'Increases XP gained by 50%',
    speed: 1.1,
    efficiency: 1.5,
    unlockLevel: 15,
    price: 500,
  },
  {
    id: 'fox',
    name: 'Garden Fox',
    icon: '🦊',
    rarity: 'rare',
    ability: 'Lucky Find',
    abilityDescription: 'Chance to find rare items while harvesting',
    speed: 1.3,
    efficiency: 1.3,
    unlockLevel: 18,
    price: 750,
  },
  
  // Epic Pets
  {
    id: 'phoenix',
    name: 'Garden Phoenix',
    icon: '🔥',
    rarity: 'epic',
    ability: 'Rebirth',
    abilityDescription: 'Instantly revives withered plants',
    speed: 1.5,
    efficiency: 2.0,
    unlockLevel: 25,
    price: 2000,
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    icon: '🦄',
    rarity: 'epic',
    ability: 'Magic Growth',
    abilityDescription: 'Reduces growth time by 30%',
    speed: 1.4,
    efficiency: 1.8,
    unlockLevel: 28,
    price: 2500,
  },
  
  // Legendary Pets
  {
    id: 'dragon',
    name: 'Garden Dragon',
    icon: '🐉',
    rarity: 'legendary',
    ability: 'Elemental Mastery',
    abilityDescription: 'Controls weather to optimize plant growth',
    speed: 2.0,
    efficiency: 3.0,
    unlockLevel: 40,
    price: 10000,
  },
  {
    id: 'fairy',
    name: 'Garden Fairy',
    icon: '🧚',
    rarity: 'legendary',
    ability: 'Time Magic',
    abilityDescription: 'Can speed up or slow down time for plants',
    speed: 1.8,
    efficiency: 2.5,
    unlockLevel: 45,
    price: 15000,
  },
];

export const TOOLS: Tool[] = [
  // Basic Tools
  {
    id: 'basic_watering_can',
    name: 'Basic Watering Can',
    icon: '🚿',
    type: 'watering',
    efficiency: 1.0,
    durability: 100,
    price: 25,
    unlockLevel: 1,
  },
  {
    id: 'wooden_hoe',
    name: 'Wooden Hoe',
    icon: '🪓',
    type: 'planting',
    efficiency: 1.0,
    durability: 80,
    price: 30,
    unlockLevel: 1,
  },
  {
    id: 'basic_sickle',
    name: 'Basic Sickle',
    icon: '⚡',
    type: 'harvesting',
    efficiency: 1.0,
    durability: 90,
    price: 35,
    unlockLevel: 2,
  },
  
  // Advanced Tools
  {
    id: 'golden_watering_can',
    name: 'Golden Watering Can',
    icon: '✨',
    type: 'watering',
    efficiency: 2.0,
    durability: 500,
    price: 500,
    unlockLevel: 15,
  },
  {
    id: 'auto_harvester',
    name: 'Auto Harvester',
    icon: '🤖',
    type: 'harvesting',
    efficiency: 3.0,
    durability: 1000,
    price: 2000,
    unlockLevel: 25,
  },
  {
    id: 'miracle_grow_sprayer',
    name: 'Miracle Grow Sprayer',
    icon: '💚',
    type: 'special',
    efficiency: 5.0,
    durability: 200,
    price: 1500,
    unlockLevel: 20,
  },
];

export const ACHIEVEMENTS = [
  {
    id: 'first_harvest',
    name: 'First Harvest',
    description: 'Harvest your first plant',
    icon: '🌱',
    reward: { xp: 10, coins: 25 },
  },
  {
    id: 'plant_collector',
    name: 'Plant Collector',
    description: 'Grow 10 different types of plants',
    icon: '🌿',
    reward: { xp: 100, coins: 500 },
  },
  {
    id: 'millionaire',
    name: 'Millionaire',
    description: 'Earn 1,000,000 coins',
    icon: '💰',
    reward: { xp: 1000, gems: 50 },
  },
  {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Harvest 100 plants in under 1 minute',
    icon: '⚡',
    reward: { xp: 500, coins: 1000 },
  },
  {
    id: 'legendary_gardener',
    name: 'Legendary Gardener',
    description: 'Reach level 50',
    icon: '👑',
    reward: { xp: 5000, gems: 200 },
  },
];

export const QUESTS = [
  {
    id: 'daily_harvest',
    title: 'Daily Harvest',
    description: 'Harvest 20 plants',
    type: 'daily' as const,
    requirements: { harvest: 20 },
    rewards: { coins: 100, xp: 50 },
    progress: { harvest: 0 },
    completed: false,
  },
  {
    id: 'weekly_variety',
    title: 'Variety Garden',
    description: 'Grow 5 different plant types this week',
    type: 'weekly' as const,
    requirements: { plant_types: 5 },
    rewards: { coins: 500, xp: 200, gems: 5 },
    progress: { plant_types: 0 },
    completed: false,
  },
];